### ISSUE TITLE
Spelling mistake in numpy syntax

### ISSUE THREAD

**Issue by syedsalman137** [DataTalksClub/machine-learning-zoomcamp#100]
On path : course-zoomcamp/02-regression/04-validation-framework.md, under heading : 2.4 Setting up the validation framework, subheading : Notes
subheading 2 : Numpy methods,

one method of numpy is given as np.arrange(), while it seemingly is np.arange()

**Comment by alexeygrigorev** [comment]
Can you please create a PR? Thank you!

**Comment by alexeygrigorev** [comment]
Fixed in #102
