### ISSUE TITLE
Timecodes for "ML Zoomcamp Office Hours"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#116]
Youtube video: https://www.youtube.com/watch?v=TXlINbcBxi8

**Comment by dimzachar** [comment]
youtube title is ML Zoomcamp Office Hours - Week #16

0:00:00 - Setting up Kubernetes and deploying a model using Docker.
0:02:54 - Installation of Kind cluster on Windows.
0:05:53 - Skipping questions, creating deployment with YAML and replacing image/port.
0:08:43 - Loading images, creating service, applying deployment on Kubernetes cluster.
0:11:52 - Kubernetes service creation and testing using port forwarding.
0:14:33 - Explanation of port forwarding and random port names.
0:17:23 - Overview of upcoming and past videos, importance of deployment.
0:19:50 - Kubernetes important for ML engineers; data scientists can skip.
0:22:34 - Data science job market and upcoming course details.
0:24:56 - Course update and upcoming projects.
0:27:44 - Course info, importance of projects, next cohort start date.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
