### ISSUE TITLE
Timecodes for "ML Zoomcamp 11.7 - Deploying with KServe and EKS"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#117]
Youtube video: https://www.youtube.com/watch?v=MpuTzBSYBBI

**Comment by dimzachar** [comment]
0:00:00 - Deploying machine learning model on AWS.
0:01:34 - Updating tutorial for K-Serve on EKS.
0:03:21 - Configuring subdomain for Kubeflow cluster creation.
0:05:11 - Instructions for creating a certificate manager.
0:06:52 - Creating a unique bucket for models.
0:08:21 - Uploading files and configuring cluster nodes.
0:10:19 - Configuring certificate for Istio load balancer.
0:11:59 - Configuring k-serve with domain and load balancer.
0:13:53 - Setting up DNS and deploying model.
0:15:59 - Deploying and testing influence service model.
0:17:48 - Deploying clothing classification model with credentials.
0:19:37 - Configuring and deploying a deep learning model.
0:21:14 - Updating predictor and testing service deployment.
0:23:11 - Debugging deployment and port issues.
0:25:39 - Deployed model successfully, cluster stopped.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
