### ISSUE TITLE
Timecodes for "ML Zoomcamp 11.6 - KServe Transformers"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#118]
Youtube video: https://www.youtube.com/watch?v=haowRqeAqJU

**Comment by dimzachar** [comment]
0:00:00 - Using transformers for pre/post-processing in k-serve
0:01:31 - Creating a transformer for image classification.
0:03:24 - Image transformation for model prediction output.
0:05:16 - Moving preprocessing logic to image transformer.
0:06:58 - Pre-processing image list for prediction.
0:08:54 - Applying prepare and post-processing to predictions.
0:10:54 - Running web service for KF model.
0:12:38 - Using arc parse to execute Python files.
0:14:23 - Configuring and starting image transformer server.
0:16:15 - Testing model with modified response printing.
0:18:05 - Fixing errors in numpy array serialization.
0:19:57 - Fixing host header issue with port forwarding.
0:21:51 - Debugging code and configuring transformer container.
0:23:46 - Building and deploying Docker image remotely.
0:25:40 - Creating a versatile image for classification tasks
0:27:27 - Troubleshooting memory issues during model deployment.
0:29:23 - Debugging Kubernetes service with Istio port forwarding.
0:31:18 - Updating K-Serve with Transformers for Internet Services.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
