### ISSUE TITLE
Timecodes for "ML Zoomcamp 11.5 - Serving TensorFlow Models with KServe"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#119]
Youtube video: https://www.youtube.com/watch?v=iXwQb2LRKGI

**Comment by dimzachar** [comment]
0:00:00 - Deploying TensorFlow models with k-serve.
0:01:38 - Creating TensorFlow inference service with K-Serve.
0:03:24 - Example of serving TensorFlow model locally.
0:05:02 - Packaging model into zip archive for download.
0:06:49 - Configuring and testing machine learning model.
0:08:45 - Invoking model from Jupiter for predictions.
0:10:29 - Sending tensor request to inference service.
0:12:23 - Converts code to script for deployment.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
