### ISSUE TITLE
Timecodes for "ML Zoomcamp 11.4 - Deploying Custom Scikit-Learn Images with KServe"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#120]
Youtube video: https://www.youtube.com/watch?v=REGNWrHZiCw

**Comment by dimzachar** [comment]
0:00:00 - Deploying custom circuit learn image with k-serve.
0:01:37 - Updating Python version and building Docker image.
0:03:24 - Updating Python and scikit-learn versions.
0:05:15 - Mounting model directory and mapping ports.
0:07:05 - Updating model to output probabilities.
0:08:54 - Updating Docker image for Churn service.
0:10:36 - Configuring resource limits for Kubernetes services.
0:12:25 - Adjusting resource limits for successful deployment.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
