### ISSUE TITLE
Timecodes for "ML Zoomcamp 11.3 - Deploying a Scikit-Learn Model with KServe"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#121]
Youtube video: https://www.youtube.com/watch?v=8kBIDggLwgE

**Comment by dimzachar** [comment]
0:00:00 - Deploying churn prediction model with k-serve
0:01:30 - Creating a Python environment with Conda.
0:03:06 - Installing specific Python version with Conda.
0:04:47 - Training model with selected features and saving.
0:06:26 - Creating a pipeline for model training.
0:08:06 - Training model and deploying with K-Server.
0:09:50 - Storing model in cloud storage options.
0:11:26 - Training and saving a model tutorial.
0:13:02 - Installing and testing Kubernetes with Scikit-learn.
0:14:50 - Executing model on k-serve container.
0:16:36 - Testing model with client data.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
