### ISSUE TITLE
Timecodes for "ML Zoomcamp 11.2 - Running KServe Locally"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#122]
Youtube video: https://www.youtube.com/watch?v=A3tFt14iTEI

**Comment by dimzachar** [comment]
0:00:00 - Installing k-serve on local Kubernetes cluster.
0:01:34 - Installing k-serve with advanced dependencies.
0:03:10 - Undoing and reinstalling Kubernetes cluster setup.
0:04:56 - Debugging Istio deployment on Kubernetes cluster.
0:06:37 - Installing and setting up K Server.
0:08:25 - Creating machine learning inference service with Scikit-learn.
0:10:03 - Check created port configuration and deployment.
0:11:44 - Deploying and testing Istio in Kubernetes.
0:13:31 - Port forwarding to access Kubernetes cluster.
0:15:17 - Creating and sending batch prediction request.
0:17:09 - Forwarding requests to specific host headers.
0:18:47 - Deploying and forwarding requests to inference service.
0:20:31 - Deploying scikit-learn model with requests.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
