### ISSUE TITLE
Timecodes for "ML Zoomcamp 11.1 - Overview"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#123]
Youtube video: https://www.youtube.com/watch?v=CFWK05dQoGM

**Comment by LoHertel** [comment]
00:00 What is KServe?
01:39 Review of previous lesson
03:23 KServe - outline for tensorflow model
04:48 KServe - outline for sklearn model
07:24 Lesson structure

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
