### ISSUE TITLE
Timecodes for "ML Zoomcamp 10.8 - Deploying to EKS"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#126]
Youtube video: https://www.youtube.com/watch?v=89jxeddZtC0

**Comment by LoHertel** [comment]
00:00 Review
00:41 Setup eksctl CLI tool
02:38 Create EKS cluster
05:06 Publish local docker images to ECR
09:05 Deploy to EKS
13:22 Test deployment
14:22 Watch resources in AWS management console
16:34 Delete EKS cluster
17:49 Summary

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
