### ISSUE TITLE
Timecodes for "ML Zoomcamp 10.7 - Deploying TensorFlow Models to Kubernetes"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#127]
Youtube video: https://www.youtube.com/watch?v=6vHLMdnjO2w

**Comment by LoHertel** [comment]
00:00 Review
01:27 Create TF model deployment
07:43 Create service for TF model deployment
09:16 Create gateway deployment
19:58 Create service for gateway deployment
21:35 Summary
22:50 Pointer for load balancing gRPC connections in production

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
