### ISSUE TITLE
Timecodes for "ML Zoomcamp 10.6 - Deploying a Simple Service to Kubernetes"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#128]
Youtube video: https://www.youtube.com/watch?v=PPUCVRIV9t8

**Comment by LoHertel** [comment]
00:00 Review
01:12 Setup ping example
04:18 Setup local Kubernetes cluster
10:23 Prepare app deployment
16:57 Deploy app into Kubernetes
20:21 Test the deployed app
22:52 Create Kubernetes service
26:46 Test Kubernetes service
28:55 Summary

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
