### ISSUE TITLE
Timecodes for "ML Zoomcamp 10.5 - Introduction to Kubernetes"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#129]
Youtube video: https://www.youtube.com/watch?v=UjVkpszDzgk

**Comment by LoHertel** [comment]
00:00 What is Kubernetes
00:53 Kubernetes cluster / nodes / pods / deployments
03:50 Services and ingress
07:35 Scaling
08:52 Scope for ML Zoomcamp
09:26 Summary

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
