### ISSUE TITLE
Timecodes for "ML Zoomcamp 10.4 - Docker-Compose"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#130]
Youtube video: https://www.youtube.com/watch?v=ZhQQfpWfkKY

**Comment by LoHertel** [comment]
00:00 Review
01:08 Create Dockerfile for model service
05:17 Create Dockerfile for prediction gateway
08:01 Running containers on a host machine
10:58 Install docker compose
14:54 Create a docker compose file
20:52 Run docker compose
23:25 Summary

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
