### ISSUE TITLE
Timecodes for "ML Zoomcamp 10.3 - Creating a Pre-Processing Service"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#131]
Youtube video: https://www.youtube.com/watch?v=OIlrS14Zi0o

**Comment by LoHertel** [comment]
00:00 Review previous lesson
00:32 Prepare prediction script
03:31 Turn script into flask service
05:08 Test flask service
06:27 Create environment for flask without tensorflow
09:06 Refactoring make_tensor_proto
10:44 Summary

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
