### ISSUE TITLE
Timecodes for "ML Zoomcamp 10.2 - TensorFlow Serving"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#132]
Youtube video: https://www.youtube.com/watch?v=deXR2fThYDw

**Comment by LoHertel** [comment]
00:00 Review previous lesson
00:29 Convert Keras model into SavedModel format
03:10 Get SavedModel signature definition
05:21 Run tf-serving in Docker
09:13 Install libraries for connection to tf-serving
11:02 Setup gRPC connection
12:56 Setup prediction service
15:16 Preprocess image into protobuf format
16:23 Run prediction
18:44 Summary

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
