### ISSUE TITLE
Timecodes for "ML Zoomcamp 10.1 - Overview"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#133]
Youtube video: https://www.youtube.com/watch?v=mvPER7YfTkw

**Comment by dimzachar** [comment]
0:00:00 - Session 10: Kubernetes & Tensorflow Serving for Image Classification
0:00:53 - Efficient TensorFlow serving for image predictions.
0:01:50 - Get pen predictions from uploaded images.
0:02:47 - Flask gateway converts numbers to predictions.
0:03:40 - JSON for website, CPU for gateway
0:04:36 - Scalable TensorFlow serving with GPU/CPU separation.
0:05:27 - Converting, deploying, and communicating with Docker.
0:06:13 - Kubernetes setup and deployment on cloud.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
