### ISSUE TITLE
Timecodes for "ML Zoomcamp Office Hours - Week #15 (project by Lisa Kirch)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#134]
Youtube video: https://www.youtube.com/watch?v=c6YMmw8ebwY

**Comment by dimzachar** [comment]
0:00:00 - Midterm project on great resignation classification.
0:01:59 - Exploring data and grouping job categories.
0:04:12 - Exploring data and fitting models visually.
0:06:15 - Visualizing decision trees and random forests.
0:08:30 - Visualizing feature importance in predicting employee turnover.
0:10:41 - Testing different models for project satisfaction.
0:12:59 - testing employee retention with machine learning.
0:16:00 - Using Google Cloud Shell for Docker deployment.
0:17:42 - Discussion on project deadline and tools used.
0:19:26 - Learning algorithms and deployment through news research.
0:21:14 - Comparing hyper parameter tuning techniques for ML.
0:22:58 - Automated model selection with beta robot.
0:24:38 - Grid search for optimal model parameters.
0:26:32 - Expert tips for cleaning data sets.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
