### ISSUE TITLE
Timecodes for "ML Zoomcamp 9.10 - Homework solution"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#137]
Youtube video: https://www.youtube.com/watch?v=4SXZfzNZ3IQ

**Comment by dimzachar** [comment]
0:00:05 - Deploying Docs vs Cats model on Windows.
0:03:16 - Converting model to smaller size using float32.
0:06:42 - Output index is 13, image resizing.
0:09:36 - Rescaling image values to 0-1 scale.
0:12:15 - Pre-processing image and accessing pixel value.
0:15:05 - Preparing code for lambda function.
0:18:46 - Testing function and Python float conversion.
0:22:22 - Preparing Docker image for TensorFlow Lite.
0:25:31 - Installing Pillow and testing Docker build.
0:29:07 - Running Docker container with port mapping.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
