### ISSUE TITLE
Timecodes for "ML Zoomcamp 9.7 - API Gateway: Exposing the Lambda Function"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#139]
Youtube video: https://www.youtube.com/watch?v=wyZ9aqQOXvs

**Comment by dimzachar** [comment]
0:00:00 - Creating a REST API for Lambda function.
0:00:54 - Creating a POST endpoint for prediction.
0:01:43 - Create post method for lambda function.
0:02:39 - Testing API Gateway deployment with URL.
0:03:35 - Creating a Lambda function web service.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
