### ISSUE TITLE
Timecodes for "ML Zoomcamp 9.6 - Creating the Lambda Function"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#140]
Youtube video: https://www.youtube.com/watch?v=kBch5oD5BkY

**Comment by dimzachar** [comment]
0:00:00 - Creating a Lambda function with Docker.
0:01:45 - Configuring and logging in to AWS registry.
0:03:19 - Using Linux's 'set' to replace password.
0:05:06 - Creating and tagging image for ECR.
0:07:09 - Pushing Docker image to ECR and creating Lambda function.
0:08:56 - Adjusting timeout and memory for AWS Lambda.
0:10:43 - AWS Lambda pricing and cost calculation.
0:12:23 - Classifying images with Lambda and cost comparison.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
