### ISSUE TITLE
Timecodes for "ML Zoomcamp 9.5 - Preparing a Docker Image"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#141]
Youtube video: https://www.youtube.com/watch?v=y4_YQjfOsDo

**Comment by dimzachar** [comment]
0:00:00 - Preparing Docker image for AWS Lambda.
0:00:54 - Installing dependencies and copying files.
0:01:59 - Command for Lambda function location in Docker.
0:02:56 - Testing Docker container with requests library.
0:04:00 - Sending requests to Docker container with JSON.
0:05:00 - Compiling TensorFlow Lite for different distributions.
0:05:51 - Get compiled TensorFlow Lite from GitHub.
0:06:48 - Testing library installation with pip install.
0:07:34 - Converting numpy array to python floats.
0:08:25 - Converting code to Docker image for deployment.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
