### ISSUE TITLE
Timecodes for "ML Zoomcamp 9.3 - TensorFlow Lite"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#143]
Youtube video: https://www.youtube.com/watch?v=OzZA4mSBE0Q

**Comment by dimzachar** [comment]
0:00:00 - Learn about TensorFlow Lite for efficiency.
0:01:41 - Using TensorFlow Lite for inference only.
0:03:44 - Classifying an image using TensorFlow Keras.
0:05:54 - Converting TensorFlow model to TensorFlow Lite.
0:07:58 - Converting Keras model to TensorFlow Lite.
0:09:48 - Manually setting input and output indexes.
0:11:30 - Initializing input, invoking computations, fetching predictions.
0:13:15 - Converting TensorFlow code to TensorFlow Lite.
0:15:11 - Resizing and preprocessing image for TensorFlow.
0:17:30 - Extracted code for image processing, simplified
0:19:18 - Resizing and preprocessing images for predictions.
0:20:51 - Loading and invoking TensorFlow Lite model.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
