### ISSUE TITLE
Timecodes for "ML Zoomcamp 9.1 - Introduction to Serverless"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#145]
Youtube video: https://www.youtube.com/watch?v=JLIVwIsU6RA

**Comment by dimzachar** [comment]
0:00:00 - Session 9: Serverless Deep Learning for Image Classification
0:00:58 - Deploying image classification model using AWS Lambda.
0:01:51 - Using TensorFlow Lite in AWS Lambda

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
