### ISSUE TITLE
Timecodes for "ML Zoomcamp 8.12 - Using the Model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#149]
Youtube video: https://www.youtube.com/watch?v=cM1WHKae1wo

**Comment by dimzachar** [comment]
0:00:00 - Using trained model for evaluation and usage.
0:00:52 - Loading model and test dataset preparation.
0:01:53 - Importing and evaluating image data in Keras.
0:02:53 - Testing data accuracy compared to dish.
0:03:45 - Uploading and processing clothing image tutorial.
0:04:48 - Pre-processing image for model detection.
0:05:44 - Converting to list, joining classes and predictions.
0:06:38 - Using model for predictions and classes.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
