### ISSUE TITLE
Timecodes for "ML Zoomcamp 8.11 - Training a Larger Model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#150]
Youtube video: https://www.youtube.com/watch?v=_QpDGJwFjYA

**Comment by dimzachar** [comment]
0:00:00 - Lesson 11: Training a larger ML model.
0:01:06 - Skipping augmentation, using checkpointing for model versions.
0:02:08 - Adjusting image size and accuracy testing.
0:03:41 - Measuring model accuracy and adding checkpoints.
0:04:55 - Adjusting learning rate to improve accuracy.
0:06:08 - Model training with image augmentation explained.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
