### ISSUE TITLE
Timecodes for "ML Zoomcamp 8.7 - Checkpointing"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#154]
Youtube video: https://www.youtube.com/watch?v=NRpGUx0o3Ps

**Comment by dimzachar** [comment]
0:00:01 - Learn how to use checkpointing in machine learning.
0:01:45 - Keras callbacks for saving model checkpoints.
0:03:34 - Keras file naming convention and best accuracy.
0:05:35 - Save best only checkpoint for accuracy.
0:07:40 - Training model with callbacks for improvement.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
