### ISSUE TITLE
Timecodes for "ML Zoomcamp 8.6 - Adjusting the Learning Rate"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#155]
Youtube video: https://www.youtube.com/watch?v=2gPmRRGz0Hc

**Comment by dimzachar** [comment]
0:00:00 - Adjusting learning rate for machine learning.
0:01:49 - Slow learning effective, but not efficient.
0:03:34 - Finding the right learning rate balance.
0:05:22 - Training model with varying learning rates.
0:07:52 - Selecting optimal learning rate for model.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
