### ISSUE TITLE
Timecodes for "ML Zoomcamp 8.4 - Convolutional Neural Networks"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#157]
Youtube video: https://www.youtube.com/watch?v=BN-fnYzbdc8

**Comment by dimzachar** [comment]
0:00:00 - Lesson 4: Understanding Convolutional Neural Networks
0:02:15 - Sliding filters to create feature maps.
0:04:25 - Convolutional layers create feature maps from filters.
0:06:56 - Progressive filters learn complex shapes in layers.
0:09:11 - Explanation of how filters work in CNNs.
0:11:18 - Image turned into vector for predictions.
0:13:28 - Building a binary classification model with logistic regression.
0:15:46 - Building models for multiple clothing classes.
0:18:11 - Explanation of dense layers in neural networks
0:20:37 - Convolutional layers turn image into vector representation.
0:23:04 - Visualizing Convolutional Layers and Pooling in Neural Networks.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you
