### ISSUE TITLE
Timecodes for "ML Zoomcamp 8.3 - Pre-Trained Convolutional Neural Networks"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#158]
Youtube video: https://www.youtube.com/watch?v=qGDXEz-cr6M

**Comment by dimzachar** [comment]
No transcript was found in the requested language for video.

**Comment by Josiah-Adesola** [comment]
Here @alexeygrigorev @amitfrancis 
------------------------------------------------
00:06 - Introduction to pre-trained CNNs
00:29 - Keras Applications pre-trained models
00:54 - Models trained on ImageNet
01:42 - Model architectures and characteristics
02:59 - Using SageMaker for TensorFlow
03:24 - Pre-processing input images
03:48 - Image classification with pre-trained model
05:01 - Adapting the model for custom use
