### ISSUE TITLE
Timecodes for "ML Zoomcamp 8.2 - Tensorflow and Keras"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#159]
Youtube video: https://www.youtube.com/watch?v=R6o_CUmoN9Q

**Comment by dimzachar** [comment]
0:00:00 - Lesson 2: TensorFlow and Keras Overview.
0:00:57 - Install TensorFlow on Anaconda or Jupyter Notebook.
0:01:45 - Installing and loading TensorFlow and Keras.
0:02:41 - Loading images with Keras in TensorFlow.
0:03:42 - Loading image with TensorFlow 2.0.
0:04:50 - Resizing images for neural networks explained.
0:06:00 - Processing images with Python's PIL library.
0:07:05 - Explanation of image encoding and array shape.
0:08:20 - Converting Pillow image to NumPy array.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
