### ISSUE TITLE
Timecodes for "ML Zoomcamp 8.1 - Fashion Classification"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#160]
Youtube video: https://www.youtube.com/watch?v=it1Lu7NmMpw

**Comment by dimzachar** [comment]
0:00:00 - Session 8: Neural Networks for Non-Tabular Data
0:00:51 - Image classification for online fashion listings.
0:01:46 - Automated fashion category suggestion using neural network.
0:02:44 - Training model to categorize clothing images.
0:03:37 - Cloning t-shirt dataset with 10 categories.
0:04:30 - Practical training, limited theory, neural networks.
0:05:24 - Overview of TensorFlow and Keras training
