### ISSUE TITLE
Timecodes for "ML Zoomcamp Office Hours - Week #7 - Midterm Project"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#164]
Youtube video: https://www.youtube.com/watch?v=wWBm6MHu5u8

**Comment by dimzachar** [comment]
0:00:16 - Introduction to Midterm Project and Guidelines
0:03:31 - Exploring data and problem description process.
0:05:16 - Expert advice on selecting and tuning models.
0:07:12 - Training and deploying ML model.
0:08:57 - Project deadline: Nov 1, peer review Nov 8.
0:11:33 - Neural nets homework deadline and guidelines.
0:13:56 - Guidelines and scoring for projects explained.
0:16:05 - Discussion on third project and certificates.
0:18:38 - Supervised vs unsupervised learning in daily work
0:20:42 - Contextual explanation of project documentation and tools.
0:22:36 - Deploying and packaging machine learning models.
0:24:27 - Project review process explained in detail.
0:26:27 - Midterm project scoring system explained.
0:28:57 - Random reviewer assignment, individual work allowed.
0:30:59 - Choosing a Good Data Set for Analysis
0:32:52 - Submitting incomplete project for feedback and grading.
0:34:51 - Discussion on model score and grading process.
0:36:55 - Minimum requirements: deploy web service in Docker, try multiple models, write good article.
0:39:01 - Guidelines for reviewing projects with Docker.
0:40:59 - Tips for choosing the best model.
0:43:00 - Deploying tutorials for AWS and alternatives.
0:45:13 - Tips for documenting model performance without test labels.
0:47:41 - Discussion on clustering and submitting assignments.
0:50:01 - Learn to expand text with shift.
0:52:07 - How to write and share articles online.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
