### ISSUE TITLE
Timecodes for "ML Zoomcamp 6.9 - Selecting the Best Model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#167]
Youtube video: https://www.youtube.com/watch?v=lqdnyIVQq-M

**Comment by dimzachar** [comment]
0:00:00 - Selecting best models for machine learning.
0:01:10 - Comparing models for best performance on validation.
0:02:22 - Training final model with full dataset.
0:03:38 - Creating feature matrix for train and test.
0:05:02 - Training and evaluating a machine learning model.
0:06:05 - XGBoost outperforms other models for tabular data.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
