### ISSUE TITLE
Timecodes for "ML Zoomcamp 6.6 - Ensemble Learning and Random Forest"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#170]
Youtube video: https://www.youtube.com/watch?v=FZhcmOfNNZE

**Comment by dimzachar** [comment]
0:00:00 - Lesson 6: Random Forest for Decision Trees
0:01:57 - Using multiple experts/models for better decisions.
0:03:49 - Using random forest for model aggregation.
0:05:46 - Training multiple models with random features.
0:07:51 - UC score validation with randomization
0:09:43 - Testing model performance with increasing estimators
0:11:41 - Plotting model performance with increasing estimators.
0:13:40 - Training models with varying max depth.
0:15:58 - Optimizing parameters for Random Forest model.
0:17:59 - Loop over s, select values, plot.
0:19:49 - Optimizing random forest model with color-coded data.
0:21:54 - Max depth, mean sample leaf, max features, bootstrap, and n_jobs parameters explained.
0:23:35 - Training multiple models in parallel for speed.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
