### ISSUE TITLE
Timecodes for "ML Zoomcamp 6.5 - Decision Trees Parameter Tuning"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#171]
Youtube video: https://www.youtube.com/watch?v=XJaxwH50Qok

**Comment by tummala-hareesh** [comment]
00:00 Introduction
00:06 Review of Previous lesson
01:35 Parameters in DecisionTreeClassifier()
02:35 Adjusting max_depth parameter
05:05 Adjusting min_samples_leaf for selected max_depth values
08:40 Pivoting DF
09:30 Visualizing as a HeatMap
13:30 Finalize a DT with parameters
13:54 Next lesson topic

@amitfrancis @alexeygrigorev

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
