### ISSUE TITLE
Timecodes for "ML Zoomcamp 6.4 - Decision Tree Learning Algorithm"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#172]
Youtube video: https://www.youtube.com/watch?v=XODz6LwKY7g

**Comment by tummala-hareesh** [comment]
00:00 Introduction 
00:10 Review - Training decision tress with sklearn
00:40 Decision tress learning
07:00 Split and Misclassification Rate/Impurity
11:04 Impurity Table to decide the split
16:24 Handling >1 features in DT split
21:01 Finding the best split algorithm
23:28 Stopping criteria for DT split
26:03 Review of the lesson

@amitfrancis  @alexeygrigorev

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
