### ISSUE TITLE
Timecodes for "ML Zoomcamp 6.3 - Decision Trees"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#173]
Youtube video: https://www.youtube.com/watch?v=YGiQvFbSIg8

**Comment by tummala-hareesh** [comment]
00:00 Introduction
00:20 What is a Decision Tree?
04:20 Decision Tree from sklearn
05:04 Train a model 
06:30 Testing on validation data
08:07 Problem of Overfitting 
11:50 Retrain the DT with max_depth=3
13:34 Export the DT  
16:50 Review of this week
17:06 Next lesson topic

@amitfrancis @alexeygrigorev

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
