### ISSUE TITLE
Timecodes for "ML Zoomcamp 6.2 - Data Cleaning and Preparation"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#174]
Youtube video: https://www.youtube.com/watch?v=tfuQdI3YO2c

**Comment by tummala-hareesh** [comment]
00:00 Introduction 
00:12 Downloading on the dataset
00:58 Loading dataset with pandas 
01:51 Standardizing column names 
02:07 Mapping encoded features data 
05:37 Descriptive statistics on the dataset 
05:57 Replace large numbers with np.nan
07:47 Convert target into numerical type
08:50 Prepare train-val-test datasets
11:32 Review of this lesson
11:45 Next lesson topic

@amitfrancis @alexeygrigorev

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
