### ISSUE TITLE
Timecodes for "ML Zoomcamp 6.1 - Credit Risk Scoring Project"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#175]
Youtube video: https://www.youtube.com/watch?v=GJGmlfZoCoU

**Comment by tummala-hareesh** [comment]
00:00 Introduction 
00:07 Review of Credit Risk Scoring project
03:55 Dataset for the credit risk project 
05:18 Brief about this week's learning 
06:23 Next lesson topic

@amitfrancis  @alexeygrigorev

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
