### ISSUE TITLE
Timecodes for "ML Zoomcamp 5.7 - Deployment To The Cloud: AWS Elastic Beanstalk (Optional)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#178]
Youtube video: https://www.youtube.com/watch?v=HGPJ4ekhcLg

**Comment by tummala-hareesh** [comment]
00:00 Introduction 
01:24 Creating an account in AWS 
03:16 Deploying web service using Elastic Beanstalk
06:05 Installing CLI for AWS EB
07:42 Use EBCLI to deploy service
08:53 Testing if the server works locally
10:21 Web service on the cloud
12:02 Testing web service hosted on the cloud
15:04 Terminate EB service
15:41 Review of the lesson
16:27 Next lesson topics

@amitfrancis

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
