### ISSUE TITLE
Timecodes for "ML Zoomcamp 5.6 - Environment Management: Docker"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#179]
Youtube video: https://www.youtube.com/watch?v=wAtyYZ6zvAs

**Comment by tummala-hareesh** [comment]
00:00 Introduction
00:27 Isolation among services using docker
04:04 Running python image with docker 
08:15 Dockerfile and building basic docker image
10:52 Running docker images
11:22 Extending Dockerfile for churn webservice
18:08 Review of this lesson
19:02 Next lesson topic 

@amitfrancis

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
