### ISSUE TITLE
Timecodes for "ML Zoomcamp 5.5 - Python Virtual Environment: Pipenv"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#180]
Youtube video: https://www.youtube.com/watch?v=BMXh8JGROHM

**Comment by tummala-hareesh** [comment]
0:10 Dependency and Env management ( bsacially how pip works )
1:42 Scenario of conflict with versions
3:42 How virtual Environment solves the issue ?
5:49 Various Virtual envs you can use
7:00 Installing Pipenv
7:25 Installing libraries with Pipenv
8:10 Explaning the Pipfile and Pipfile.lock files created by Pipenv
13:02 Running  things pipenv

@amitfrancis @alexeygrigorev 

I was working on it and did see your (@alexeygrigorev ) comment. So, adding this comment to close this issue. Thanks to @MekongDelta-mind for sharing the timecodes.

**Comment by amitfrancis** [comment]
Updated the timecodes. Thank you so much!

**Comment by MekongDelta-mind** [comment]
Sorry for not replying to the prev comment (@alexeygrigorev ). Was bit busy with work and personal issue. 
Thanks @tummala-hareesh for taking the initiative, adding the required info and closing the issue.
