### ISSUE TITLE
Timecodes for "ML Zoomcamp 5.4 - Serving the Churn Model with Flask"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#181]
Youtube video: https://www.youtube.com/watch?v=Q7ZWPgPnRz8

**Comment by tummala-hareesh** [comment]
00:00 Introduction
00:28 Brief on turning churn prediction into web service
01:10 Creating churn predict web service
02:19 Handling JSON for web service - input, output 
05:25 Churn web service in debug mode - Error 500
06:18 Communicating with Churn service - browser Error
09:48 Production Web Service   - gunicorn
15:58 Review of the Lesson 
16:19 Next Lesson topics


@amitfrancis

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
