### ISSUE TITLE
Timecodes for "ML Zoomcamp 5.3 - Web Services: Introduction to Flask"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#182]
Youtube video: https://www.youtube.com/watch?v=W7ubna1Rfv8

**Comment by tummala-hareesh** [comment]
00:00 Introduction 
00:15 Brief on Churn Service  as Web Service
00:35 What is Web Service? 
01:58 Create a simple web service 
02:48 Turn ping into web service
05:07 Using curl to communicate with web service
05:42 Using browser to communicate with web service 
06:06 Review  
06:30 Next Lesson Topic


@amitfrancis

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
