### ISSUE TITLE
Timecodes for "ML Zoomcamp 5.2 - Saving and Loading the Model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#183]
Youtube video: https://www.youtube.com/watch?v=EJpqZ7OlwFU

**Comment by de-Ann-Hickey** [comment]
00:00 Intro
00:19 Combining previous weeks' code into one notebook
01:03 Running code in notebook
01:43 Save the model with pickle
05:26 Restart kernel and load the model
07:38 Turning the notebook into a Python script

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
