### ISSUE TITLE
Timecodes for "ML Zoomcamp 5.1 - Intro / Session Overview"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#184]
Youtube video: https://www.youtube.com/watch?v=agIFak9A3m8

**Comment by tummala-hareesh** [comment]
00:00 Introduction 
00:42 How to use ML model from notebook?   
01:42 Focus of this week 
02:05 Plan for this week
03:15 Details about the plan for the week  
04:10 Next lesson 

@amitfrancis

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
