### ISSUE TITLE
Timecodes for "ML Zoomcamp 4.7 - Cross-Validation"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#187]
Youtube video: https://www.youtube.com/watch?v=BIIZaVtUbf4

**Comment by de-Ann-Hickey** [comment]
0:00 Intro
0:22 K-fold cross validation 
03:10 Create a train function
04:35 Create a predict function
05:22 Create the Kfold object
06:29 Using the kfold.split() method
07:55 Train a model for each fold and calculate roc_auc_score
09:44 Using the tqdm library
11:18 Parameter tuning
14:49 Train final model
16:27 When to use cross validation

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
