### ISSUE TITLE
Timecodes for "ML Zoomcamp 4.6 - ROC AUC"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#188]
Youtube video: https://www.youtube.com/watch?v=hvIQPAwkVZo

**Comment by de-Ann-Hickey** [comment]
0:00 Intro
04:16 Implementing the auc function
06:00 Implementing the roc_auc_score function
07:05 AUC Interpretation
12:48 Vectorizing the AUC with np.random
15:17 Summary

**Comment by amitfrancis** [comment]
Updated timecodes, Thank you!
