### ISSUE TITLE
Timecodes for "ML Zoomcamp 4.5 Continued - Plotting ROC Curves With Scikit-Learn"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#189]
Youtube video: https://www.youtube.com/watch?v=B5PATo1J6yw

**Comment by tummala-hareesh** [comment]
00:00  Introduction 
00:19 Example of Radar Detectors for ROC usage
01:00 Two metrics - FPR and TPR 
02:06 FPR from confusion matrix 
02:45 TPR from confusion matrix
04:54 Python computation of FPR and TPR 
06:05 ROC curve 
09:48 Plotting ROC curve
11:52 Random baseline to compare model
14:40 Plotting random baseline ROC curve
16:10 Ideal model as different benchmark
22:02 Plotting ideal model ROC curve
23:36 Putting everything together
25:35 Plotting only TPR vs FPR
32:12 TPR vs FPR - How to interpret model performance?
34:00 Next Session - AUC 

@amitfrancis

**Comment by amitfrancis** [comment]
hi @tummala-hareesh, seems like there's an error with the timecodes. The video is only 1 min and 57 secs

**Comment by tummala-hareesh** [comment]
@amitfrancis  that's correct. These timecodes are for actual video which was already closed. Sorry. My bad !

https://github.com/alexeygrigorev/mlbookcamp-code/issues/190

**Comment by amitfrancis** [comment]
Okay, no worries! Thanks
