### ISSUE TITLE
Timecodes for "ML Zoomcamp 4.5 - ROC Curves"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#190]
Youtube video: https://www.youtube.com/watch?v=dnBZLk53sQI

**Comment by de-Ann-Hickey** [comment]
0:00 TPR and FPR
11:48 Random model
16:08 Ideal model
23:38 Putting everything together

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
