### ISSUE TITLE
Timecodes for "ML Zoomcamp 4.4 - Precision and Recall"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#191]
Youtube video: https://www.youtube.com/watch?v=gRLP_mlglMM

**Comment by tummala-hareesh** [comment]
00:00 Review of previous lesson
00:40 Accuracy formulation
01:09 Precision definition 
01:24 Precision calculation for churn example
05:35 Recall calculation for churn example
10:01 Accuracy is misleading for churn example
11:30 Recap of Precision and Recall 
14:20 Summary 

@amitfrancis

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks
