### ISSUE TITLE
Timecodes for "ML Zoomcamp 4.1 - Evaluation Metrics: Session Overview"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#194]
Youtube video: https://www.youtube.com/watch?v=gmg5jw1bM8A

**Comment by tummala-hareesh** [comment]
00:00 Introduction 
00:10 Recap of previous week
00:40 Other ways of evaluating the binary classification models? 
01:24 Overview of accuracy and dummy model 
02:00 Overview of Confusion table
02:05 Overview of Precision and Recall
02:15 Overview of ROC Curves
02:45 Overview of ROC-AUC 
03:00 Overview of Cross-Validation 
03:22 What's in Next Lesson?

@amitfrancis

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks
