### ISSUE TITLE
Timecodes for "ML Zoomcamp 3.12 - Using the Model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#197]
Youtube video: https://www.youtube.com/watch?v=Y-NGmnFpNuM

**Comment by dimzachar** [comment]
0:00:00 - Training final model using all features.
0:02:01 - Train and test logistic regression model.
0:04:22 - Analyzing model accuracy and customer data
0:06:14 - Transforming customer data for model prediction.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
