### ISSUE TITLE
Timecodes for "ML Zoomcamp 3.9 - Logistic Regression"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#200]
Youtube video: https://www.youtube.com/watch?v=7KFE2ltnBAg

**Comment by dimzachar** [comment]
No transcript was found in the requested language for video.

**Comment by Josiah-Adesola** [comment]
Here @alexeygrigorev 

00:06 Coefficients and Weights in Logistic Regression

00:11 Impact of Contract Types on Churn Probability

00:14 Negative Weights and Churn Probability

00:00 Introduction to Python's Zip Function

00:01 How Zip Function Works with Examples

00:22 Training a Smaller Logistic Regression Model

00:28 Selected Features for the Smaller Model

00:33 Creating a Dictionary Vectorizer

00:39 Scoring Customers with Logistic Regression Model

00:47 Interpreting Scores and Churn Probability

00:56 Interpreting Logistic Regression Weights

01:01 Significance of Negative Weights

**Comment by amitfrancis** [comment]
Timecodes updated! Thank you!
