### ISSUE TITLE
Timecodes for "ML Zoomcamp 3.8 - One-Hot Encoding"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#201]
Youtube video: https://www.youtube.com/watch?v=L-mjQFN5aR0

**Comment by dimzachar** [comment]
0:00:00 - Lesson 8: Encoding categorical variables with one-hot encoding
0:02:33 - Encoding categorical variables using one-hot encoding.
0:04:51 - Implementing one-hot-encoding with DictVectorizer.
0:06:57 - Learning and transforming data with sparse matrix.
0:08:52 - Using DictVectorizer for one-hot encoding.
0:10:57 - Creating dictionaries for train data variables.
0:13:11 - Creating feature matrix using dictionary vectorizer.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
