### ISSUE TITLE
Timecodes for "ML Zoomcamp 3.7 - Feature Importance: Correlation"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#202]
Youtube video: https://www.youtube.com/watch?v=mz1707QVxiY

**Comment by dimzachar** [comment]
0:00:00 - Lesson 7: Understanding Pearson's Correlation Coefficient
0:02:08 - Moderate to strong correlation between variables.
0:04:43 - Correlation between numerical variables and churn rate.
0:07:09 - Churn rate decreases with longer tenure.
0:09:17 - Monthly charges affect churn rate correlation.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
