### ISSUE TITLE
Timecodes for "ML Zoomcamp 3.6 - Feature Importance: Mutual Information"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#203]
Youtube video: https://www.youtube.com/watch?v=_u2YaGT6RN0

**Comment by dimzachar** [comment]
0:00:00 - Lesson 6: Measuring importance of categorical variables
0:01:21 - Using mutual information to predict churn.
0:02:50 - Target variable and feature values importance.
0:04:14 - Relative importance of variables analyzed with function.
0:05:42 - Column-wise mutual information score sorting.
0:07:05 - Importance of variables in machine learning.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
