### ISSUE TITLE
Timecodes for "ML Zoomcamp 3.5 - Feature Importance: Churn Rate And Risk Ratio"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#204]
Youtube video: https://www.youtube.com/watch?v=fzdzPLlvs40

**Comment by dimzachar** [comment]
0:00:00 - Lesson 5: Analyzing Churn Rate in Groups
0:01:16 - Analyzing Churn Rates by Gender and Partner.
0:02:44 - Churn rate varies by partner status.
0:04:10 - Measuring teaching importance through churn rates.
0:05:35 - Risk ratio reveals partner's impact on churn
0:07:07 - Comparing churn rates for different groups.
0:08:43 - High-risk groups identified for churning analysis.
0:10:14 - Group by gender, calculate average churn.
0:11:22 - Calculating churn rate by gender and variables.
0:12:42 - Using a function to display loop output.
0:14:07 - Predictive variables for customer churn likelihood.
0:15:21 - Internet service & contract affect churning likelihood
0:16:35 - Insights on important variables for churn prediction.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
