### ISSUE TITLE
Timecodes for "ML Zoomcamp 3.4 - EDA"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#205]
Youtube video: https://www.youtube.com/watch?v=BNF1wjBwTQA

**Comment by dimzachar** [comment]
0:00:00 - Exploratory data analysis on full train dataset.
0:01:16 - Calculating churn rate using value counts.
0:02:40 - Computing mean gives us churn rate.
0:04:01 - Analyzing churn and categorical/numerical variables.
0:05:34 - Selecting categorical variables and counting unique values.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
