### ISSUE TITLE
Timecodes for "ML Zoomcamp 3.2 - Data Preparation"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#207]
Youtube video: https://www.youtube.com/watch?v=VSGGU9gYvdg

**Comment by dimzachar** [comment]
0:00:00 - Lesson 2: Download and preprocess data with Pandas.
0:01:14 - Transposing data frame to view columns.
0:02:31 - Data preparation for consistent column names.
0:03:57 - Exploring data types and converting values.
0:05:10 - Replacing missing data with 'not a number'.
0:06:30 - Filling missing values and converting churn variable.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
