### ISSUE TITLE
Timecodes for "ML Zoomcamp 3.1 - Churn Prediction Project"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#208]
Youtube video: https://www.youtube.com/watch?v=0Zw04wdeTQo

**Comment by dimzachar** [comment]
0:00:00 - Week 3: Machine learning for churn prediction.
0:01:15 - Identifying customer churn likelihood with personalized offers.
0:02:31 - Preventing customer churn with accurate discounts using machine learning.
0:03:40 - Formula for predicting customer churn.
0:05:02 - Model predicts customer churn likelihood.
0:06:23 - Building a model to predict churn.
0:07:45 - Exploratory data analysis with cycler and encoding.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
