### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.16 - Car Price Prediction Project Summary"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#210]
Youtube video: https://www.youtube.com/watch?v=_qI01YXbyro

**Comment by dimzachar** [comment]
0:00:00 - Summarizing machine learning regression project.
0:01:36 - Training a linear regression model.
0:03:07 - Exploring metrics and feature engineering techniques.
0:04:32 - Improved model performance with categorical variables.
0:05:54 - Training final model and applying predictions.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
