### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.15 - Using The Model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#211]
Youtube video: https://www.youtube.com/watch?v=KT--uIJozes

**Comment by dimzachar** [comment]
0:00:00 - Training final model on full dataset.
0:01:17 - Combining train and test data frames.
0:02:57 - Concatenating data for model training and testing.
0:04:38 - Final model can predict car price accurately.
0:05:48 - Creating a dictionary for car pricing model.
0:07:17 - Creating a data frame for prepare_x.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
