### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.14 - Tuning the Model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#212]
Youtube video: https://www.youtube.com/watch?v=lW-YVxPgzQw

**Comment by dimzachar** [comment]
0:00:00 - Finding best regularization parameter for linear regression.
0:01:25 - Printing regularization, bias, and score results.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
