### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.13 - Regularization"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#213]
Youtube video: https://www.youtube.com/watch?v=91ve3EJlHBc

**Comment by VikhyatSharma17** [comment]
I am taking this up

**Comment by VikhyatSharma17** [comment]
0:00    Introduction
0:07    Previous lesson recap
0:47    Problem description - Linear Combination
5:45    Problem Solution - Regularization
9:32    Regularization Implementation
11:28    Summary
11:37    Next lesson precap

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
