### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.12 - Categorical Variables"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#214]
Youtube video: https://www.youtube.com/watch?v=sGLAToAAMa4

**Comment by dimzachar** [comment]
0:00:00 - Lesson 12: Understanding Categorical Variables in Machine Learning
0:01:20 - Encoding categorical variables with binary columns.
0:02:43 - Converting categorical column to binary columns.
0:04:04 - Creating columns for car doors using loop.
0:05:36 - Deleting categorical variables and modifying prepare x.
0:07:19 - Appending new features to a list.
0:08:43 - Top 5 popular car makes listed.
0:10:06 - Adding car makes to improve results.
0:11:36 - Creating dictionary of top vehicle categories.
0:13:07 - Creating categorical variables from popular values.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
