### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.11 - Feature Engineering"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#215]
Youtube video: https://www.youtube.com/watch?v=-aEShw4ftB0

**Comment by dimzachar** [comment]
0:00:00 - Adding car age variable to model.
0:01:10 - Modifying data frame to add feature.
0:02:30 - Function creates copy to avoid data modification.
0:04:00 - Improved model with validation data set.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
