### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.10 - Computing RMSE on Validation Data"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#216]
Youtube video: https://www.youtube.com/watch?v=rawGPXg2ofE

**Comment by dimzachar** [comment]
0:00:00 - Validating machine learning model using validation data.
0:01:13 - Creating feature matrix with prepare x function.
0:02:28 - Training and validating linear regression model.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
