### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.9 - Root Mean Squared Error"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#217]
Youtube video: https://www.youtube.com/watch?v=0LWoFtbzNUM

**Comment by VikhyatSharma17** [comment]
I am taking this up

**Comment by VikhyatSharma17** [comment]
0:00    Introduction
0:13    Recap of the last lesson
0:36    RMSE Formula
0:55    RMSE Formula Explanation
5:35    RMSE Python Implementation
7:22    Next lession precap

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
