### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.8 - Baseline Model for Car Price Prediction Project"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#218]
Youtube video: https://www.youtube.com/watch?v=SvPpMMYtYbU

**Comment by dimzachar** [comment]
0:00:00 - Building a baseline car price model.
0:01:23 - Extracting basic features for linear regression.
0:03:24 - Dealing with missing values in data modeling
0:05:14 - Replacing missing values with zeros for training.
0:06:42 - Training data predictions plotted for comparison.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
