### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.7 - Training Linear Regression: Normal Equation"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#219]
Youtube video: https://www.youtube.com/watch?v=hx6nak-Y11g

**Comment by VikhyatSharma17** [comment]
I am taking this up

**Comment by VikhyatSharma17** [comment]
0:00        Introduction
0:11        Recap                       
0:24        Problem Description
1:10        LR Simple Equation Solution
2:09        LR Simple Equation Solution Issues
2:49        LR Normal Equation Solution
4:54        Normal Equation Proof References
5:29        Normal Equation Python Implementation
13:58      Code Output Explanation
14:49      Creating Training Function

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
