### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.6 - Linear Regression: Vector Form"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#220]
Youtube video: https://www.youtube.com/watch?v=YkyevnYyAww

**Comment by tummala-hareesh** [comment]
00:00 Introduction
00:07 Recap 
00:42 Recap of linear regression - single vector
01:18 Linear regression - vector form - dot product
01:53 Linear regression - dot product implementation
03:24 Linear regression - shorter notation
07:15 All Examples - matrix notation
10:20 Perform matrix vector multiplication
12:50 Implementation of linear_regression() 
13:20 Summary
14:02 Next Topics

@amitfrancis completed Timecodes for # 2.6

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
