### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.5 - Linear Regression"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#221]
Youtube video: https://www.youtube.com/watch?v=Dn1eTQLsOdA

**Comment by AaishaMuhammad** [comment]
0:00 Intro
0:07 What is Linear Regression 
1:33 Simplified form
3:24 Example on training data 
6:51 Implementation
9:21 Implementation in code
13:11 Breakdown explanation
17:13 Getting exponents
18:41 Summary

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
