### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.4 - Setting Up The Validation Framework"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#222]
Youtube video: https://www.youtube.com/watch?v=ck0IfiPaQi0

**Comment by de-Ann-Hickey** [comment]
Not sure if I got the terminology correct :-) Please change if needed


0:00 Intro
1:38 Split dataframe into train, test, and validation
4:50 Create the new dataframes
7:29 Shuffle the records in dataframe
13:48 Reset the indices of each dataframe
14:48 Get the target variables (y)
15:55 Remove the msrp from the dataframes
17:04 Summary

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
