### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.3 - Exploratory Data Analysis"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#223]
Youtube video: https://www.youtube.com/watch?v=k6k8sQ0GhPM

**Comment by de-Ann-Hickey** [comment]
0:00 Intro
2:20 Returning unique values in series
5:02 Visualize the dataset
7:05 Long tail distribution
11:00 Apply logarithmic distribution
14:57 Plot the normal distribution
16:08 Look at missing values
17:40 Summary

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
