### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.2 - Data Preparation"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#224]
Youtube video: https://www.youtube.com/watch?v=Kd74oR4QWGM

**Comment by de-Ann-Hickey** [comment]
0:00 Intro
0:43 Download the dataset
1:12 Load the dataset
3:02 Normalize the dataset

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
