### ISSUE TITLE
Timecodes for "ML Zoomcamp 2.1 - Car Price Prediction Project"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#225]
Youtube video: https://www.youtube.com/watch?v=vM3SqPNlStE

**Comment by VikhyatSharma17** [comment]
I am taking this up.

**Comment by VikhyatSharma17** [comment]
Timecodes

0:00    Introduction
0:12    Problem Description
0:52    Dataset information
2:35    Project Plan Step1
2:46    Project Plan Step2
2:57    Project Plan Step3
3:10    Project Plan Step4
3:25    Project Plan Step5
3:35    Project Plan Step6
3:52    Project Plan Step7
3:56    Code Repo details
5:12    Next video precap

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
