### ISSUE TITLE
Timecodes for "ML Zoomcamp 1.9 - Introduction to Pandas"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#228]
Youtube video: https://www.youtube.com/watch?v=0j3XK5PsnxA

**Comment by de-Ann-Hickey** [comment]
0:00 Intro
0:20 Import pandas
0:34 DataFrames
5:00 Series
8:30 Index
9:28 Accessing elements
13:26 Element-wise operations
15:37 Filtering
17:06 String operations
20:47 Summarizing operations
23:56 Missing values
25:18 Grouping
27:10 Getting the NumPy arrays

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
