### ISSUE TITLE
Timecodes for "ML Zoomcamp 1.8 - Linear Algebra Refresher"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#229]
Youtube video: https://www.youtube.com/watch?v=zZyKUeOR4Gg

**Comment by de-Ann-Hickey** [comment]
0:00 Intro
0:20 Vector operations
2:42 Vector-vector multiplication
9:45 Matrix-vector multiplication
16:50 Matrix-matrix multiplication
23:31 Identity matrix
25:38 Matrix inverse

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
