### ISSUE TITLE
Timecodes for "ML Zoomcamp 1.7 - Introduction to NumPy"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#230]
Youtube video: https://www.youtube.com/watch?v=Qa0-jYtRdbY

**Comment by de-Ann-Hickey** [comment]
I'll do this one :)

**Comment by de-Ann-Hickey** [comment]
0:00 Intro
0:40 Import numpy
1:14 Creating arrays
5:38 Multi-dimensional arrays
10:28 Randomly generated arrays
14:02 Element-wise operations
17:15 Comparison operations
19:50 Summarizing operations

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thanks!
