### ISSUE TITLE
Timecodes for "ML Zoomcamp 1.5 - Model Selection Process"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#231]
Youtube video: https://www.youtube.com/watch?v=OH_R0Sl9neM

**Comment by AaishaMuhammad** [comment]
0:00 Introduction
1:02 Holdout + Train
3:28 Making Predictions
6:54 Scoring
7:58 Multiple Comparisons Problem
13:12 Train + Validation + Test
15:17 Further scoring
16:28 Model Selection (6 steps)
20:49 Summary

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thanks!
