### ISSUE TITLE
Timecodes for "ML Zoomcamp 1.2 - ML vs Rule-Based Systems"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#234]
Youtube video: https://www.youtube.com/watch?v=CeukwyUdaz8

**Comment by AaishaMuhammad** [comment]
doing the timecodes for this one!

**Comment by AaishaMuhammad** [comment]
0:00 Introduction
0:37 Rule based Systems
6:26 Use Machine Learning!
7:56 Features
11:41 Model outputs
14:22 Summary

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thanks Aaisha!
