### ISSUE TITLE
Timecodes for "ML Zoomcamp 1.1 - Introduction to Machine Learning"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#235]
Youtube video: https://www.youtube.com/watch?v=Crm_5n4mvmg

**Comment by abhinit21** [comment]
0:10 Car Classifieds example
4:30 What is ML model ?
7:50 Model Training
8:30 Predictions
9:20 Next Lecture

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
