### ISSUE TITLE
Timecodes for "Machine Learning Zoomcamp - Learn Machine Learning Engineering in Four Months"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#236]
Youtube video: https://www.youtube.com/watch?v=rowoDjPc8HU

**Comment by abhinit21** [comment]
This is **Previous video**

![image](https://user-images.githubusercontent.com/58618233/188719789-b6bb77ff-d184-497d-a863-18da6d632526.png)

### Timecodes already exists for the video

**Comment by alexeygrigorev** [comment]
Thank you!
