### ISSUE TITLE
Timecodes for "Machine Learning Zoomcamp 2022"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#238]
Youtube video: https://www.youtube.com/watch?v=MqI8vt3-cag

**Comment by abhinit21** [comment]
I am taking up this

**Comment by abhinit21** [comment]
0:00 Introduction
2:20 Team
3:55 Perquisites
5:20 Repo
7:40 About the Course
21:25 Course Logistics
27:50 FAQ's
30:00 Course Logistics
35:10 Leaderboard & Scoring
41:50 Timecodes
43:55 Stats
44:55 DataTalks.Club Slack
49:45 Sponsor
52:45 Q&A

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thank you!
