### ISSUE TITLE
Timecodes for "ML Zoomcamp 2022 - Office Hours #1"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#270]
Youtube video: https://www.youtube.com/watch?v=VojpszKmKw8

**Comment by dimzachar** [comment]
0:00:00 - Thanking viewers for contributions and updates.
0:01:49 - Tips for contributing to time codes.
0:03:47 - Overview of Week 2 content and homework
0:05:46 - How to structure technical interviews around projects
0:07:40 - Course overview and live coding demonstration.
0:09:35 - Emphasis on projects, not trivia questions.
0:11:24 - Late homework submission not accepted.
0:13:08 - Importance of Projects over Homeworks in Certification
0:15:14 - Intuition-based distribution shaping and homework evaluation.
0:17:27 - Using pandas for large data sets.
0:19:27 - Learn how to run machine learning in your database.
0:21:18 - Scikit-learn offers smarter ways for regression.
0:23:18 - Collect unique data for impactful project.
0:25:15 - Collecting data for portfolio projects is amazing.
0:27:06 - Career advice: Data engineer or scientist?
0:28:50 - Data science vs. data engineering & linear regression assumptions.
0:30:51 - Practical validation for linear regression models.
0:32:54 - Choosing an ideal tech stack for data science
0:34:56 - Deploying Docker containers with AWS Batch.
0:36:57 - Cross-validation best for improving model score.
0:39:07 - Data science course covers modeling and deployment.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
