### ISSUE TITLE
Timecodes for "ML Zoomcamp 2022 - Homework 1 solution"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#271]
Youtube video: https://www.youtube.com/watch?v=J0Ht4V9mIRI

**Comment by dimzachar** [comment]
title is ML Zoomcamp 2022 - Homework #1 solution by Timur Kamaliev

**Comment by dimzachar** [comment]
0:00:01 - Introduction and overview of homework.
0:02:46 - How to analyze data set using pandas functions
0:05:52 - Explaining detecting missing values and calculating median/mode.
0:08:46 - Filling missing values, applying normal equation, matrix multiplication.
0:11:52 - Explanation of linear regression using matrix multiplication.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
