### ISSUE TITLE
Update 2022 cohorts page to include Week 04 Homeword

### ISSUE THREAD

**Issue by davidcolton** [DataTalksClub/machine-learning-zoomcamp#290]
This page does not have the link to the Week 04 homework.

https://github.com/alexeygrigorev/mlbookcamp-code/tree/master/course-zoomcamp/cohorts/2022

**Comment by alexeygrigorev** [comment]
PR with a fix is welcome

**Comment by alexeygrigorev** [comment]
But I think it was fixed already
