### ISSUE TITLE
While converting keras to tflite error

### ISSUE THREAD

**Issue by saisubramani** [DataTalksClub/machine-learning-zoomcamp#3]
While converting keras to tflite error :

`raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
ValueError: ('Unrecognized keyword arguments:', dict_keys(['ragged']))
`

`Traceback (most recent call last):
  File "convert.py", line 5, in <module>
    model = keras.models.load_model('xception_v4_large_08_0.894.h5')`

**Comment by alexeygrigorev** [comment]
Which version of tensorflow do you use?

**Comment by saisubramani** [comment]
Hi ,sorry for Late reply!
My tensorflow version is 1.14.0

**Comment by alexeygrigorev** [comment]
Okay! That explains it. Try a newer version, at least 2.0

**Comment by saisubramani** [comment]
Thanks got it, i converted successfully!

**Comment by alexeygrigorev** [comment]
Happy to hear
