### ISSUE TITLE
notes correction in 06 Decision Trees...

### ISSUE THREAD

**Issue by lucapug** [DataTalksClub/machine-learning-zoomcamp#315]
Inside 02-data-prep.md , in the train/val/test split bullet note at the moment is :
"Split the data with the distribution of 80% train, 20% validation, and 20% test sets with random seed to 11"

should be:

Split the data with the distribution of 60% train, 20% validation, and 20% test sets with random seed to 11

**Comment by alexeygrigorev** [comment]
can you please open a PR? thank you

**Comment by bsenst** [comment]
Hi @lucapug I wanted to create the Pull Request but couldn't find the cited passage.

- https://github.com/alexeygrigorev/mlbookcamp-code/search?q=Split+the+data+with+the+distribution+of+80%25+train%2C+20%25+validation%2C+and+20%25+test+sets+with+random+seed+to+11
- https://github.com/alexeygrigorev/mlbookcamp-code/search?q=02-data-prep.md

@lucapug where did you find this text passage?

**Comment by lucapug** [comment]
I can read it here:
https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/06-trees/02-data-prep.md

it is at the 6th bullet point.

**Comment by bsenst** [comment]
> I can read it here: https://github.com/alexeygrigorev/mlbookcamp-code/blob/master/course-zoomcamp/06-trees/02-data-prep.md
> 
> it is at the 6th bullet point.

@lucapug thanks for the hint. pull request has been created. have a nice weekend 😃
