### ISSUE TITLE
Timecodes for "ML Zoomcamp 7.1 - Intro/Session Overview"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#322]
Youtube video: https://www.youtube.com/watch?v=2viqmJ_NpgE

**Comment by dimzachar** [comment]
0:00:00 - Module 7: Introduction to Bento ML.
0:01:05 - Deploying credit prediction model through API.
0:02:21 - Learn to build and deploy ML services.
0:03:30 - Consider operational efficiency for scalable services.
0:04:37 - Understanding the components of machine learning.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
