### ISSUE TITLE
Timecodes for "ML Zoomcamp 7.2 - Building Your Prediction Service with BentoML"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#323]
Youtube video: https://www.youtube.com/watch?v=bWdEVlUw1CA

**Comment by dimzachar** [comment]
0:00:00 - Building a prediction service using XGBoost.
0:01:12 - Saving ML model with BentoML framework.
0:02:44 - Creating and referencing unique model versions.
0:04:16 - Creating a service endpoint with BentoML.
0:05:46 - Pass application data, predict with model.
0:07:26 - Setting up BentoML service with Swagger UI.
0:08:57 - Debugging inference API with Bento ML.
0:10:25 - Saving custom objects for model support.
0:11:48 - Using 'latest' convention for model updates.
0:13:25 - Testing and adding prediction logic.
0:15:27 - Processing data and returning business results.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
