### ISSUE TITLE
Timecodes for "ML Zoomcamp 7.3 - Deploying Your Prediction Service"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#324]
Youtube video: https://www.youtube.com/watch?v=qpjLm_Lm4FA

**Comment by dimzachar** [comment]
0:00:00 - Learn to deploy prediction service with Bento.
0:01:18 - Importance of saving framework version in Bento.
0:02:34 - Configuring Bento file for lightweight packaging.
0:03:50 - Specify Python packages and environment variables.
0:05:10 - Building a Bento with dependencies.
0:06:39 - Automated Swagger UI and Docker file generation.
0:07:49 - Standardized Bento container for machine learning deployment.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
