### ISSUE TITLE
Timecodes for "ML Zoomcamp 7.4 - Sending, Receiving and Validating Data"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#325]
Youtube video: https://www.youtube.com/watch?v=zNYtXde0BCA

**Comment by dimzachar** [comment]
0:00:00 - Validating and cleaning received JSON data.
0:01:22 - Creating a data schema with Pedantic.
0:02:50 - Validating JSON fields for data accuracy.
0:04:41 - Transforming data for model prediction accuracy.
0:06:38 - Different data types for schema and parsing.
0:07:59 - Validating shape of ND arrays in Python.
0:09:39 - Validating data shape and type enforcement.
0:11:50 - Learn to use Bento ML API.
0:13:16 - Sending and receiving image data tutorial.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
