### ISSUE TITLE
Timecodes for "ML Zoomcamp 7.5 - High-Performance Serving"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#326]
Youtube video: https://www.youtube.com/watch?v=LjDYPWhJBrY

**Comment by dimzachar** [comment]
0:00:00 - Learn high-performance model surveying with Locust
0:01:13 - Locust runs JSON requests at high speed.
0:02:34 - Optimizing request latency with async await.
0:04:06 - Async-await allows parallel processing of requests.
0:05:23 - Fast API allows parallelization at endpoint & inference.
0:06:44 - Testing server performance with increasing requests
0:08:24 - Optimizing service with process replication.
0:09:59 - Micro batching for efficient model input processing.
0:11:15 - Enabling batch processing for machine learning model.
0:12:53 - Optimizing web worker efficiency with batching.
0:14:35 - Basic performance optimizations and batching configuration.
0:16:01 - Optimizing batch size and latency for models.

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
