### ISSUE TITLE
Timecodes for "ML Zoomcamp 7.6 - Bento Production Deployment"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#327]
Youtube video: https://www.youtube.com/watch?v=aF-TfJXQX-w

**Comment by dimzachar** [comment]
0:00:00 - Building and deploying Bento with AWS ECS
0:01:18 - Building Bento ML container for deployment.
0:03:00 - Creating AWS container registry and pushing image.
0:04:22 - Get AWS CLI, access keys, push ECR.
0:05:42 - Connecting to AWS and pushing Docker image.
0:07:24 - Tagging, pushing, and running Docker image.
0:09:09 - Steps to create an Amazon GPU cluster.
0:10:47 - Selecting Fargate and creating task definition.
0:12:37 - Setting soft limit and port mapping.
0:14:03 - Creating and configuring Fargate tasks.
0:15:32 - Deploying a Production Service in the Cloud.
0:16:57 - Deploying and sharing Bento ML services.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
