### ISSUE TITLE
Timecodes for "ML Zoomcamp 7.7 - (Optional) Advanced Example: Deploying Stable Diffusion Model"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/machine-learning-zoomcamp#328]
Youtube video: https://www.youtube.com/watch?v=NMIi_DDVxAs

**Comment by dimzachar** [comment]
0:00:02 - Introducing Stable Diffusion: Text to Image Model.
0:01:18 - Creating a virtual environment and installing dependencies.
0:02:42 - Importing pre-built Bento model with curl.
0:04:21 - Configuring custom Runner for Stable Diffusion.
0:05:44 - Using Stable Diffusion to Generate Images with Text.
0:07:05 - Specify hardware and resources for Runner.
0:08:22 - Creating a Runner for ML predictions.
0:09:47 - Pre-processing image and text inputs.
0:11:06 - Specify fields, directories, and Cuda version.
0:12:25 - Deploying Bento ml service with Bento CTL.
0:13:59 - Deploying Bento CTL to AWS and more.
0:15:28 - Installing Bento CTL and Terraform for AWS deployment.
0:17:13 - Building and deploying Docker to EC2.
0:18:52 - Launching EC2 machine for stable diffusion.

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
