### ISSUE TITLE
Heart Attack Analysis

### ISSUE THREAD

**Issue by harshita9621** [DataTalksClub/machine-learning-zoomcamp#41]
- I want to performed in-depth Exploratory Data Analysis and 5-6 Algoritrhm.

- Dataset: https://www.kaggle.com/rashikrahmanpritom/heart-attack-analysis-prediction-dataset

Assign me this issue under Hacktoberfest'21.

**Comment by alexeygrigorev** [comment]
Sure, just go for it =)

Not sure how can I assign it to you (and why)

**Comment by harshita9621** [comment]
@Why the issue are closed, I want to work on it

**Comment by alexeygrigorev** [comment]
feel free to work on it, I'm not sure why you need an open issue for that
